micronaut:
  application:
    name: taskalog

notificators:
  - 'com.github.theirish81.notifications.TalMailNotification'

tickers:
  tasks_seconds: 10
  timers_seconds: 10

ingresses:
  - 'com.github.theirish81.ingresses.TalRabbitIngress'