micronaut:
  application:
    name: taskalog

notificators:
  - 'com.github.theirish81.taskalog.notifications.TalMailNotification'
  - 'com.github.theirish81.taskalog.notifications.TalRabbitNotification'

tickers:
  tasks_seconds: 10
  timers_seconds: 10

ingresses:
  - 'com.github.theirish81.taskalog.ingresses.TalRabbitIngress'